#!/bin/bash -ex

# read all the configuration parameters first
source ../config.conf
export EXTRAMAPPER_DIR=$EXTRAMAPPERDIR

dataDir=${EXTRAMAPPER_DIR}/preprocess/data
dataDirPerPair=${EXTRAMAPPER_DIR}/preprocess/data/$org1-$org2
referenceGenomesDir=$dataDir/reference_genomes
chainsDir=$dataDir/liftover_chains
ensemblDir=$dataDirPerPair/ensemblDownloads

# Download supp data from article http://www.ncbi.nlm.nih.gov/pubmed/19883501
	if [[ ! -f Dataset_s2_Human_and_mouse_orthologous_exons_list.tsv ]]; then
		rm -rf gb-2009-10-11-r120-S5.zip # remove if it is there
		wget https://static-content.springer.com/esm/art%3A10.1186%2Fgb-2009-10-11-r120/MediaObjects/gb-2009-10-11-r120-S5.zip --no-check-certificate
		unzip gb-2009-10-11-r120-S5.zip
		rm -rf gb-2009-10-11-r120-S5.zip
		# this below link does not work anymore after GB changed interface
		#wget http://genomebiology.com/content/supplementary/gb-2009-10-11-r120-s5.zip
		#unzip gb-2009-10-11-r120-s5.zip
	fi

  # and also download necessary liftover files to convert:
	# hg18 to hg38 coordinates
	if [[ ! -f $chainsDir/hg18/liftOver/hg18ToHg38.over.chain.gz ]]; then
		mkdir -p $chainsDir/hg18/liftOver
		wget http://hgdownload.cse.ucsc.edu/goldenPath/hg18/liftOver/hg18ToHg38.over.chain.gz --directory-prefix=$chainsDir/hg18/liftOver
	fi

	# mm8 to mm10 coordinates
	if [[ ! -f $chainsDir/mm8/liftOver/mm8ToMm10.over.chain.gz ]]; then
		mkdir -p $chainsDir/mm8/liftOver
		wget http://hgdownload.cse.ucsc.edu/goldenPath/mm8/liftOver/mm8ToMm10.over.chain.gz --directory-prefix=$chainsDir/mm8/liftOver
	fi

# Convert the coordinates from the original publication to the reference genome versions used in ExTraMapper

	# note that exon names are missing from these files, only the transcript names are those NM...
	cat Dataset_s2_Human_and_mouse_orthologous_exons_list.tsv | awk 'NR>1{print $7"\t"$8"\t"$9"\t"NR"\t"$5"\t"$10}' > human_exons-hg18.bed
	cat Dataset_s2_Human_and_mouse_orthologous_exons_list.tsv | awk 'NR>1{print $11"\t"$12"\t"$13"\t"NR"\t"$3"\t"$14}' > mouse_exons-mm8.bed

	chainFile=$chainsDir/hg18/liftOver/hg18ToHg38.over.chain.gz
	${EXTRAMAPPER_DIR}/preprocess/bin/liftOver human_exons-hg18.bed $chainFile hg38.mapped hg38.unmapped

	chainFile=$chainsDir/mm8/liftOver/mm8ToMm10.over.chain.gz
	${EXTRAMAPPER_DIR}/preprocess/bin/liftOver mouse_exons-mm8.bed $chainFile mm10.mapped mm10.unmapped

	cat hg38.mapped | sort -k1,1 -k2,2n | tr -s '\t' > hg38.mapped.sorted
	cat mm10.mapped | sort -k1,1 -k2,2n | tr -s '\t' > mm10.mapped.sorted

	hg38exons=${EXTRAMAPPER_DIR}/preprocess/data/human-mouse/liftoverRelatedFiles/org1_allExonsList.bed
	mm10exons=${EXTRAMAPPER_DIR}/preprocess/data/human-mouse/liftoverRelatedFiles/org2_allExonsList.bed

	bedtools intersect -a $hg38exons -b hg38.mapped.sorted -sorted -wao > hg38.mapped.intAll
	bedtools intersect -a $mm10exons -b mm10.mapped.sorted -sorted -wao > mm10.mapped.intAll

	cat hg38.mapped.intAll |\
		awk '$6!="." {l1=$3-$2; l2=$8-$7; if (($4==$11) && (l1-l2<2 && l2-l1<2) && ($NF==l1 || $NF==l2)) print $9"\t"$1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$10}' |\
		sort -k1,1  > hg38.mapped.int
	cat mm10.mapped.intAll |\
		awk '$6!="." {l1=$3-$2; l2=$8-$7; if (($4==$11) && (l1-l2<2 && l2-l1<2) && ($NF==l1 || $NF==l2)) print $9"\t"$1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$10}' |\
		sort -k1,1  > mm10.mapped.int

	join hg38.mapped.int mm10.mapped.int | sort -k1,1n | awk -v OFS="\t" '{print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13}' \
		| sort -u -k1,12 > Human_and_mouse_orthologous_exons-Ensembl-hg38-to-mm10.txt


	# Number of unique exons and exon pairings using exon coordinates BEFORE conversion to hg38-mm10
	cat Dataset_s2_Human_and_mouse_orthologous_exons_list.tsv | awk 'NR>1{print $7":"$8"-"$9}' | sort | uniq | wc -l # human exons
	cat Dataset_s2_Human_and_mouse_orthologous_exons_list.tsv | awk 'NR>1{print $11":"$12"-"$13}' | sort | uniq | wc -l # mouse exons
	cat Dataset_s2_Human_and_mouse_orthologous_exons_list.tsv | awk 'NR>1{print $11":"$12"-"$13,$7":"$8"-"$9}' | sort | uniq | wc -l # pairings

	# Number of unique exons and exon pairings using exon coordinates AFTER conversion to hg38-mm10
	cat Human_and_mouse_orthologous_exons-Ensembl-hg38-to-mm10.txt  | awk '{print $1":"$2"-"$3}' | sort | uniq | wc -l # human exons 
	cat Human_and_mouse_orthologous_exons-Ensembl-hg38-to-mm10.txt  | awk '{print $7":"$8"-"$9}' | sort | uniq | wc -l # mouse exons
	cat Human_and_mouse_orthologous_exons-Ensembl-hg38-to-mm10.txt  | awk '{print $1":"$2"-"$3,$7":"$8"-"$9}' | sort | uniq | wc -l # pairings

	mv hg38.mapped human_exons-hg38.bed
	mv mm10.mapped mouse_exons-mm10.bed
	rm -rf a b hg38.mapped* mm10.mapped* *.unmapped

